services:
  - type: web
    name: spring-backend
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/Backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: spring-db
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: spring-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: spring-db
          property: password

databases:
  - name: spring-db
    databaseName: dbportfolio
    user: postgres
